json.id @product.id
json.user_id @product.user_id
json.category_id @product.category_id
json.modality @product.modality
json.product_type_id @product.product_type_id
json.brand @product.brand
json.name @product.name
json.description @product.description
json.price_in_cents @product.price_in_cents
json.quantity @product.quantity
json.photoa @product.photos
